services:
  server:
    build: ./server
    image: server:latest
    container_name: server
    networks:
      - server_net
    expose:
      - 8050
    ports:
      - "127.0.0.1:8050:8050"
  
  scraper:
    build: ./scraper
    image: scraper:latest
    container_name: scraper
    networks:
      - server_net
    depends_on:
      - server

networks:
  server_net:
    driver: bridge
